// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TempProject.Models
{
    public partial class sp_upgraddiagramsResult
    {
    }
}
